// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swjlaltsvbrzstuwmdst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3amxhbHRzdmJyenN0dXdtZHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTM1MDYsImV4cCI6MjA2NzQ4OTUwNn0.vTgLMAVdC0ve0k3JRYwXmcXTY67mNGBph5hP4Za7uKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});